change version to 1.1

diff --git a/tests/ocrTests b/tests/ocrTests
--- a/tests/ocrTests
+++ b/tests/ocrTests
@@ -40,12 +40,28 @@ while [[ $# -gt 0 ]]; do
     elif [[ "$1" = "-ext_labeling" ]]; then
         shift
         TEST_EXT_LABELING=yes
+    elif [[ "$1" = "-ext_params_evt" ]]; then
+        shift
+        TEST_EXT_PARAMS_EVT=yes
+    elif [[ "$1" = "-ext_counted_evt" ]]; then
+        shift
+        # Need both
+        TEST_EXT_PARAMS_EVT=yes
+        TEST_EXT_COUNTED_EVT=yes
+    elif [[ "$1" = "-ext_channel_evt" ]]; then
+        shift
+        TEST_EXT_PARAMS_EVT=yes
+        TEST_EXT_COUNTED_EVT=yes
+        TEST_EXT_CHANNEL_EVT=yes
     elif [[ "$1" = "-co" ]]; then
         shift
         STEP_COMPILE_ONLY="yes"
     elif [[ "$1" = "-ro" ]]; then
         shift
         STEP_RUN_ONLY="yes"
+    elif [[ "$1" = "-loop" ]]; then
+        shift
+        LOOP_UNTIL_CRASH="yes"
     elif [[ "$1" = "-valgrind" && $# -ge 2 ]]; then
         shift
         WRAPPER="valgrind"
@@ -60,11 +76,19 @@ while [[ $# -gt 0 ]]; do
 done
 
 # try to lookup for a default ocr install
+if [ -z "${OCR_TYPE}" ]; then
+    echo "OCR_TYPE is not set, defaulting to x86"
+    export OCR_TYPE=x86
+fi
+
 if [ -z "${OCR_INSTALL}" ]; then
-    echo "OCR_INSTALL is not set, defaulting to ../install/x86"
-    OCR_INSTALL_TMP=`pwd`/../install/x86
-    if [ -x ${OCR_INSTALL_TMP}/lib/libocr.so ]; then
+    echo "OCR_INSTALL is not set, defaulting to ../install"
+    OCR_INSTALL_TMP=`pwd`/../install
+    if [ -e ${OCR_INSTALL_TMP}/lib/libocr_${OCR_TYPE}.so ]; then
         export OCR_INSTALL=${OCR_INSTALL_TMP}
+    else
+        echo "Error ${OCR_INSTALL_TMP}/lib/libocr_${OCR_TYPE}.so not found..."
+        exit 1
     fi
 fi
 
@@ -79,12 +103,12 @@ if [ -z "${CC}" ]; then
 fi
 
 export INCLUDES="-I${OCR_INSTALL}/include"
-
-if [[ ("$OCR_INSTALL" =~ "mpi") || ("$OCR_INSTALL" =~ "gasnet") ]]; then
-    export CFLAGS=" -Wall -g -Werror -DOCR_ENABLE_EDT_NAMING -DOCR_ASSERT -DENABLE_EXTENSION_AFFINITY"
-else
-    export CFLAGS=" -Wall -g -Werror -DOCR_ENABLE_EDT_NAMING -DOCR_ASSERT -DENABLE_EXTENSION_AFFINITY -DENABLE_EXTENSION_PAUSE"
-fi
+# See bug #894
+#if [[ ("$OCR_INSTALL" =~ "mpi") || ("$OCR_INSTALL" =~ "gasnet") ]]; then
+export CFLAGS=" -Wall -g -Werror -DOCR_ENABLE_EDT_NAMING -DOCR_ASSERT -DENABLE_EXTENSION_AFFINITY"
+#else
+#    export CFLAGS=" -Wall -g -Werror -DOCR_ENABLE_EDT_NAMING -DOCR_ASSERT -DENABLE_EXTENSION_AFFINITY -DENABLE_EXTENSION_PAUSE"
+#fi
 
 if [ -n "${TEST_EXT_RTAPI}" ]; then
     CFLAGS="$CFLAGS -DENABLE_EXTENSION_RTITF"
@@ -98,12 +122,64 @@ if [ -n "${TEST_EXT_LABELING}" ]; then
     CFLAGS="$CFLAGS -DENABLE_EXTENSION_LABELING"
 fi
 
-export LDFLAGS="-L${OCR_INSTALL}/lib -locr -lpthread ${OCR_LDFLAGS}"
+if [ -n "${TEST_EXT_PARAMS_EVT}" ]; then
+    CFLAGS="$CFLAGS -DENABLE_EXTENSION_PARAMS_EVT"
+fi
+
+if [ -n "${TEST_EXT_COUNTED_EVT}" ]; then
+    CFLAGS="$CFLAGS -DENABLE_EXTENSION_COUNTED_EVT"
+fi
+
+if [ -n "${TEST_EXT_CHANNEL_EVT}" ]; then
+    CFLAGS="$CFLAGS -DENABLE_EXTENSION_CHANNEL_EVT"
+fi
+
+CFLAGS="$CFLAGS -DOCR_TYPE_H=${OCR_TYPE}.h"
+
+export LDFLAGS="-L${OCR_INSTALL}/lib -locr_${OCR_TYPE} -lpthread ${OCR_LDFLAGS}"
 export OCR_TESTS_BIN_OUTPUT=
 
+
+# Generates an OCR configuration file
 if [ -z "${OCR_CONFIG}" ]; then
-    export OCR_CONFIG=${OCR_INSTALL}/config/generated.cfg
-    ../scripts/Configs/config-generator.py --output ${OCR_CONFIG}
+    #default values
+    export CFGARG_THREADS=${CFGARG_THREADS-8}
+    export CFGARG_ALLOCTYPE=${CFGARG_ALLOCTYPE-mallocproxy}
+    export CFGARG_DBTYPE=${CFGARG_DBTYPE-Lockable}
+    if [ -n "${TEST_EXT_LABELING}" ]; then
+        export CFGARG_GUID=${CFGARG_GUID-LABELED}
+    fi
+    if [ "${OCR_TYPE}" = "x86-mpi" ]; then
+        export CFGARG_GUID=${CFGARG_GUID-COUNTED_MAP}
+        export CFGARG_TARGET=${CFGARG_TARGET-mpi}
+    elif [[ "${OCR_TYPE}" = "x86-gasnet" ]]; then
+        export CFGARG_GUID=${CFGARG_GUID-COUNTED_MAP}
+        export CFGARG_TARGET=${CFGARG_TARGET-gasnet}
+    elif [[ "${OCR_TYPE}" = "tg-x86" ]]; then
+        echo "error: ocrrun cannot call config-generator for tg-x86 (not supported - set OCR_CONFIG)"
+        exit 1
+    fi
+
+    CFG_ARGS=""
+    # Read all CFGARG_ environment variables and transform them into config generator's arguments
+    for cfgarg in `env | grep CFGARG_`; do
+        #Extract argument name and value
+        parsed=(${cfgarg//=/ })
+        argNameU=${parsed[0]#CFGARG_}
+        if [[ ${BASH_VER} -eq 4 ]]; then
+            argNameL=${argNameU,,}
+        else
+            argNameL=`echo ${argNameU} | tr '[:upper:]' '[:lower:]'`
+        fi
+        # toLower ${argNameU} argNameL
+        argValue=${parsed[1]}
+        #Append to generator argument list
+        arg="--${argNameL} ${argValue}"
+        CFG_ARGS+="$arg "
+    done
+
+    export OCR_CONFIG=${OCR_INSTALL}/share/ocr/config/${OCR_TYPE}/generated_ocrTests.cfg
+    ${OCR_INSTALL}/share/ocr/scripts/Configs/config-generator.py ${CFG_ARGS} --output ${OCR_CONFIG} --remove-destination
     echo "OCR_CONFIG is not set, defaulting to ${OCR_CONFIG}"
 fi
 
@@ -116,7 +192,7 @@ export OCR_FLAGS=" -ocr:cfg ${OCR_CONFIG}"
 BIN_DIR=${OCR_INSTALL}/bin
 LIB_DIR=${OCR_INSTALL}/lib
 
-if [ -x ${LIB_DIR}/libocr.so -o -e ${LIB_DIR}/libocr.a ]; then
+if [ -e ${LIB_DIR}/libocr_${OCR_TYPE}.so -o -e ${LIB_DIR}/libocr_${OCR_TYPE}.a ]; then
     echo "OCR library found in ${OCR_INSTALL}/lib"
 else
     echo "ERROR OCR library not found in ${OCR_INSTALL}/lib"
@@ -139,7 +215,6 @@ export LD_LIBRARY_PATH=${LIB_DIR}:${LD_LIBRARY_PATH}
 #
 # generic runTests will be inlined
 #
-
 
 
 function ext_usage () {
@@ -166,6 +241,12 @@ function usage () {
     echo "       -perftest     : Run performance tests as non-regression tests"
     echo "       -showoutput   : Show test output on console"
     echo "       -v            : Prints additionnal information"
+    echo "       -ext_rtapi       : Enable extension runtime API"
+    echo "       -ext_legacy      : Enable extension legacy support"
+    echo "       -ext_labeling    : Enable extension labelled GUIDs"
+    echo "       -ext_params_evt  : Enable extension parameterize events"
+    echo "       -ext_counted_evt : Enable extension counted events"
+    echo "       -ext_channel_evt : Enable extension channel events"
     echo "  (-h) --help        : Prints this message"
 }
 
@@ -291,6 +372,11 @@ function compile () {
     cd $FOLDER;
     NAME=
     get_name ${FILE}
+    if [[ "${OCR_ASAN}" = "yes" ]]; then
+        ASAN_FLAGS=" -g -fsanitize=address -fno-omit-frame-pointer"
+        CFLAGS+=${ASAN_FLAGS}
+        LDFLAGS+=${ASAN_FLAGS}
+    fi
     echo "${CC} ${OCR_CFLAGS} ${CFLAGS} ${INCLUDES} ${FILE} -o ${BIN_GEN_DIR}/${NAME} ${LDFLAGS}"
     ${CC} ${OCR_CFLAGS} ${CFLAGS} ${INCLUDES} ${FILE} -o ${BIN_GEN_DIR}/${NAME} ${LDFLAGS}
     RES=$?
@@ -321,8 +407,20 @@ function run () {
     if [ -f ${TEST_RES_FILE} ]; then
         TEST_RES=`cat ${TEST_RES_FILE}`
     fi
-    echo "ocrrun ${RUN_WRAPPER} ${BIN_GEN_DIR}/${NAME} ${OCR_FLAGS} ${TEST_ARGS}"
-    ocrrun ${RUN_WRAPPER} ${BIN_GEN_DIR}/${NAME} ${OCR_FLAGS} ${TEST_ARGS}
+    echo "ocrrun_${OCR_TYPE} ${RUN_WRAPPER} ${BIN_GEN_DIR}/${NAME} ${OCR_FLAGS} ${TEST_ARGS}"
+
+    if [[ "$LOOP_UNTIL_CRASH" == "yes" ]]; then
+        let i=0;
+        RES=0;
+        while (( $RES == 0)); do
+            echo "==== Loop until crash iteration $i ===="
+            ocrrun_${OCR_TYPE} ${RUN_WRAPPER} ${BIN_GEN_DIR}/${NAME} ${OCR_FLAGS} ${TEST_ARGS}
+            RES=$?
+            let i=$i+1
+        done
+    else
+        ocrrun_${OCR_TYPE} ${RUN_WRAPPER} ${BIN_GEN_DIR}/${NAME} ${OCR_FLAGS} ${TEST_ARGS}
+    fi
     RES=$?
     if [[ $RES -eq $TEST_RES ]]; then
         RES=0;
@@ -541,6 +639,7 @@ function print_test_status () {
     local RUN=0
     local FAIL=0
     local ERR=0
+    local COLOR=39
 
     if [[ $STATUS -eq $RUN_STATUS ]]; then
         # No pbs
@@ -550,15 +649,17 @@ function print_test_status () {
 
     if [[ $STATUS -eq $FAIL_STATUS ]]; then
         # RAN but didn't verified
+        COLOR=31
         FAIL=1
     fi
 
     if [[ $STATUS -eq $ERR_STATUS ]]; then
         # didn't compiled
+        COLOR=31
         ERR=1
 fi
 
-    echo "Tests run: $RUN, Failures: $FAIL, Errors: $ERR"
+    echo -e "\033[${COLOR}mTests run: $RUN, Failures: $FAIL, Errors: ${ERR}\033[m"
 }
 
 
@@ -897,7 +998,7 @@ function runTests () {
     local BIN_GEN_DIR=
     local PATTERN=
     local EXCL_PATTERN=
-    local UNSTABLE_EXT=ignored
+    local UNSTABLE_EXT="${OCR_TYPE}-lockableDB"
     OPTION_SWEEPING="-"
     OPT_SWEEP_NULL="-"
     RUN_UNSTABLE=
@@ -980,7 +1081,6 @@ function runTests () {
 
     if [ -z ${LOG_DIR} ]; then
         LOG_DIR=`pwd`/tests-log
-        echo "Set logdir pampam"
     fi
 
     if [ -d ${LOG_DIR} ]; then
@@ -1012,7 +1112,7 @@ function runTests () {
     # If no unstable file is provided as argument
     # Check if default unstable file exists
     if [ -z "$UNSTABLE_FILE" ]; then
-        DEFAULT_UNSTABLE_FILE=${SCRIPT_NAME}.${UNSTABLE_EXT}
+        DEFAULT_UNSTABLE_FILE=unstable.${UNSTABLE_EXT}
         if [ -f "${DEFAULT_UNSTABLE_FILE}" ]; then
             UNSTABLE_FILE=${DEFAULT_UNSTABLE_FILE}
         else
